# Check coding standards

resources:
  repositories:
  - repository: azure-pipelines
    name: botika-wabis/azure-pipelines
    type: git
    ref: main

trigger:
  - main

extends:
  template: javascript/coding-standards.yml@azure-pipelines

