# Update Changelog

resources:
  repositories:
  - repository: azure-pipelines
    name: botika-wabis/azure-pipelines
    type: git
    ref: main

trigger:
  tags:
    include:
    - v*

extends:
  template: update-changelog.yml@azure-pipelines
